Develop nav bar
Photoapp-Team/FOTOFI-FRONTEND pull request #4
Opened 2022-10-18 07:22 UTC by Josdandar

Se agrego la estructura basica del Navbar - falta responsividad y trabajar con el tamano de los botones.

2022-10-18 13:53 UTC, alepaez-dev requested changes
@Josdandar resuelve los conflictos. 

Localmente...
1 - Vete a develop
2 - Git pull
3 - Regresa a esta rama
4 - git merge develop
5 - Te saldran conflictos arreglalos
6 - git push y pide review de tus compañeros

2022-10-19 13:38 UTC, alepaez-dev approved these changes
Nice
@Josdandar necesitamos la funcionalidad de subir/arrastrar imagenes, comprimirlas, y subirlas a s3 aws, te veo de 7 a 10 pair programming para acomodar el front y back

2022-10-19 13:39 UTC, alepaez-dev requested changes
nvm el approve esto tiene conflictos otra vez, ya mergearon a develop nuevas cosas, lo que hicimos ayer lo tienes que volver a hacer, jamas mergeas con conflictod

2022-10-21 01:59 UTC, alepaez-dev requested changes

2022-10-21 01:59 UTC, alepaez-dev commented on src/styles/buttonSize.js
> +// export const buttonSize = styled(Button)(()=>({
tienes comentarios, eliminalos si no los vas a necesitar

2022-10-21 08:24 UTC, deathmarcus approved these changes
Igual y vamos a tener que mover el Navbar en el Body, al menos en la parte de profile, para lograr que el navbar quede encima de la foto de portada, no arriba, pero fuera de eso bien!

2022-10-25 01:30 UTC, closed without merging